/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package g4s21p4dse;

/**
 *
 * @author Ideapad 330
 */
public class frmprincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmprincipal
     */
    public frmprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        isuma = new javax.swing.JMenuItem();
        iresta = new javax.swing.JMenuItem();
        idividir = new javax.swing.JMenuItem();
        imultiplicar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenido.setBackground(new java.awt.Color(51, 255, 204));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        jMenu1.setText("Operaciones");

        isuma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        isuma.setText("Suma");
        isuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isumaActionPerformed(evt);
            }
        });
        jMenu1.add(isuma);

        iresta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        iresta.setText("Resta");
        iresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irestaActionPerformed(evt);
            }
        });
        jMenu1.add(iresta);

        idividir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        idividir.setText("Dividir");
        idividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idividirActionPerformed(evt);
            }
        });
        jMenu1.add(idividir);

        imultiplicar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK));
        imultiplicar.setText("Multiplicar");
        imultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imultiplicarActionPerformed(evt);
            }
        });
        jMenu1.add(imultiplicar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca de");

        jMenuItem3.setText("Infromacion");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isumaActionPerformed
        // TODO add your handling code here:
        frmsuma FRMSUMA = new frmsuma();
        FRMSUMA.setVisible(true);
        contenido.add(FRMSUMA);
    }//GEN-LAST:event_isumaActionPerformed

    private void irestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irestaActionPerformed
        // TODO add your handling code here:
        frmresta FRMRESTA = new frmresta();
        FRMRESTA.setVisible(true);
        contenido.add(FRMRESTA);
    }//GEN-LAST:event_irestaActionPerformed

    private void idividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idividirActionPerformed
        // TODO add your handling code here:
        frmdivision FRMDIVISION = new frmdivision();
        FRMDIVISION.setVisible(true);
        contenido.add(FRMDIVISION);
    }//GEN-LAST:event_idividirActionPerformed

    private void imultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imultiplicarActionPerformed
        // TODO add your handling code here:
        frmmultiplicacion FRMMULTIPLICACION = new frmmultiplicacion();
        FRMMULTIPLICACION.setVisible(true);
         contenido.add(FRMMULTIPLICACION);
    }//GEN-LAST:event_imultiplicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane contenido;
    private javax.swing.JMenuItem idividir;
    private javax.swing.JMenuItem imultiplicar;
    private javax.swing.JMenuItem iresta;
    private javax.swing.JMenuItem isuma;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
